

name: Coding Style

on: ['push', 'pull_request']

jobs:
  cs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.parallel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress

      - name: Run Pint
        run: php vendor/bin/pint --test -v
